import { Toaster } from "react-hot-toast";
import "./globals.css";
import Provider from "./components/Provider";
import Appbar from "./components/Appbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Blogify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Provider>
          <Toaster />
          <Appbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
